### ISSUE TITLE
The integrated source control (Git) is very very slow in the latest version (1.78.x)

### ISSUE THREAD

**Issue by gh-egs-vividcloud** [microsoft/vscode#183199]
Type: <b>Performance Issue</b>

Before, the integrated source control (Git) in VSC is very fast but now it is very very slow. I'm not sure but this seems to happen after I update my VSC to the latest version (1.78.x). I thought that the problem is at my installed "git for Windows" (it worked well before I updated VSC) and updated it to the latest version but nothing changed, I think this is a problem of the latest version of VSC, or maybe at 1 of git extensions I installed but I'm not sure.

Note: If I use git through Git Bash, everything is still fine (fast as it should be)

Here are some log in the git output inside VSC:
2023-05-23 16:46:35.054 [info] > git add -A -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [27846ms]

2023-05-23 16:48:39.228 [info] > git ls-files --stage -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [2601ms]
2023-05-23 16:48:39.231 [info] > git ls-tree -l HEAD -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [2608ms]
2023-05-23 16:48:39.239 [info] > git ls-files --stage -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [2529ms]

2023-05-23 16:50:24.957 [info] > git ls-tree -l HEAD -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [105697ms]
2023-05-23 16:50:24.958 [info] > git ls-tree -l HEAD -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [105701ms]

2023-05-23 16:50:27.984 [info] > git ls-files --stage -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [65005ms]
2023-05-23 16:50:27.987 [info] > git ls-files --stage -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.json [65011ms]

2023-05-23 16:52:58.511 [info] > git add -A -- D:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees\appsettings.Development.json [29306ms]

2023-05-23 16:53:44.880 [info] > git fetch [16761ms]

2023-05-23 16:55:37.421 [info] > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - [100953ms]

2023-05-23 16:55:43.820 [info] > git show --textconv :CompanyEmployees/appsettings.json [2493ms]
2023-05-23 16:55:43.820 [info] > git show --textconv :CompanyEmployees/appsettings.Development.json [2479ms]

2023-05-23 16:56:12.377 [info] > git pull --tags origin main [31072ms]

2023-05-23 16:56:35.825 [info] > git push origin main:main [23445ms]

Do not know why it took so much time for the basic operations (files in my repo are quite small, nothing big/huge at all)

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (13.95GB free)|
|Process Argv|--crash-reporter-id e283a491-24a6-4982-a709-f965337f0fd8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	 25844	code main
    0	    91	  4200	shared-process
    0	    71	 14160	     ptyHost
    0	     7	 23176	       console-window-host (Windows internal process)
    0	     5	 25972	       "C:\Program Files\Git\bin\bash.exe"
    0	    11	 33292	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	   382	 18912	extensionHost [1]
    0	    76	  1904	     electron-nodejs ("D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\server\dist\node\workerMain" --node-ipc --clientProcessId=18912)
    0	    78	  4436	     electron-nodejs ("D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "d:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18912)
    0	    78	  9060	     electron-nodejs ("D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Luat Nguyen\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js" --node-ipc --clientProcessId=18912)
    0	   125	 28156	     electron-nodejs ("D:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Luat Nguyen\.vscode\extensions\streetsidesoftware.code-spell-checker-2.20.4\packages\_server\dist\main.js" --node-ipc --clientProcessId=18912)
    0	    25	 31636	     "C:\Program Files\Microsoft\jdk-17.0.7.7-hotspot\bin\java" -DwatchParentProcess=false -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError "-XX:HeapDumpPath=c:\Users\Luat Nguyen\AppData\Roaming\Code\User\globalStorage\redhat.vscode-xml" -Xmx64M -cp "c:\Users\Luat Nguyen\.vscode\extensions\redhat.vscode-xml-0.25.0-win32-x64\server\org.eclipse.lemminx-0.25.0-uber.jar" org.eclipse.lemminx.XMLServerLauncher
    0	     6	 31916	       console-window-host (Windows internal process)
    0	   556	 33392	     dotnet.exe "c:\Users\Luat Nguyen\.vscode\extensions\ms-dotnettools.csharp-1.25.7-win32-x64\.omnisharp\1.39.6-net6.0\OmniSharp.dll" -z -s d:\src\zero\main\ASPdotNET-Web-BE-Zero\CompanyEmployees.sln --hostPID 18912 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin "c:\Users\Luat Nguyen\.vscode\extensions\ms-dotnettools.csharp-1.25.7-win32-x64\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll" FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store FileOptions:SystemExcludeSearchPatterns:5=**/Thumbs.db FileOptions:SystemExcludeSearchPatterns:6=**/.classpath FileOptions:SystemExcludeSearchPatterns:7=**/.project FileOptions:SystemExcludeSearchPatterns:8=**/.settings FileOptions:SystemExcludeSearchPatterns:9=**/.factorypath FormattingOptions:EnableEditorConfigSupport=true Sdk:IncludePrereleases=true formattingOptions:useTabs=false formattingOptions:tabSize=2 formattingOptions:indentationSize=2
    0	     6	  4804	       console-window-host (Windows internal process)
    0	    40	 24088	   utility-network-service
    0	   293	 24300	window [1] (MAIN-ZERO-ASPdotNET-Web-BE (Workspace))
    0	   114	 24460	   gpu-process
    0	    80	 26432	fileWatcher [1]
    0	    25	 26516	   crashpad-handler
    0	   100	 30084	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (MAIN-ZERO-ASPdotNET-Web-BE (Workspace))
|    Folder (ASPdotNET-Web-BE-Zero): 355 files
|      File types: cs(129) cache(36) json(22) csproj(9) props(9) targets(9)
|                  txt(9) editorconfig(9) v2(2) vsidx(2)
|      Conf files: csproj(9) sln(1);
```

</details>
<details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
copy-relative-path|ale|0.0.2
All-Autocomplete|Ati|0.0.26
compare-view|che|0.13.0
vscode-better-align|cho|1.4.2
path-intellisense|chr|2.8.4
bracket-select|chu|2.0.2
vscode-structurizr|cia|0.0.9
gitignore|cod|0.9.0
csharp-grammar-extended|dan|1.1.1
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|13.6.0
LogFileHighlighter|emi|2.16.0
json-tools|eri|1.0.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
auto-using|Fud|0.7.15
copilot|Git|1.86.82
todo-tree|Gru|0.0.226
output-colorizer|IBM|0.1.2
open-file-from-path|jac|1.3.4
vscode-text-pastry|jkj|1.3.1
vscode-peacock|joh|4.2.2
workspace-cacheclean|Mam|0.0.2
render-crlf|med|1.6.1
vscode-filesize|mkx|3.1.0
csharp|ms-|1.25.7
vscode-dotnet-pack|ms-|1.0.12
remote-explorer|ms-|0.4.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.27.0
vscode-thunder-client|ran|2.7.1
vscode-xml|red|0.25.0
partial-diff|ryu|1.4.3
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.4.1
svg-preview|Sim|2.8.3
cucumber|ste|0.14.0
code-spell-checker|str|2.20.4
ASPNETCore-VSCode-Extensions|Syn|21.2.3
Blazor-VSCode-Extensions|Syn|21.2.3
c4-dsl-extension|sys|3.4.1
bracket-padder|via|0.3.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.5.1
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
j16hj152:30706079
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by gh-egs-vividcloud** [comment]
Additional info: I downgraded VSC to v1.77.3 ("GitLens" extension is downgraded to 13.5.0 also because its latest version is not compatible with VSC v1.77.3) and everything is much better. Sometimes staging and un-staging files are still slow a little bit but acceptable.

**Comment by chriscarreau** [comment]
Same thing happened to me, a simple git diff was taking ~10 seconds with the new version. I downgraded to v1.77.3 and it also fixed my issue

**Comment by ChristianCiach** [comment]
I pulled some Ansible galaxy collections into my workspace (which changed a few hundred files) and the whole computer froze for several minutes. Never had this issue with previous versions of VSCode.

Using Fedora Linux 38.

**Comment by rafidka** [comment]
I am not sure whether this is related, but GitLens started taking %100 CPU recently. I tracked the issue down to GitLens after removing all plugins and reinstalling them. Finally, I was able to discover that simply disabling/enabling GitLens was removing/reintroducing the CPU spike issue. My installation clean (since I tried to do a [clean](https://code.visualstudio.com/docs/setup/uninstall#_linux) uninstall while trying to fix the issue). I am on Linux (Fedora) and I don't have Mcafee anti-virus. If it helps here is the offending process on my machine:

```
rafid      98244  4.3  0.1 1176530436 174984 ?   Sl   12:56   0:13 /usr/share/code/code --type=utility --utility-sub-type=node.mojom.NodeService --lang=en-US --service-sandbox-type=none --enable-crash-reporter=8e552b7c-bb79-42bc-a9b4-fb0b1b3eefec,no_channel --user-data-dir=/home/rafid/.config/Code --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,11251309795413797203,11639842389012394509,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess
```

**Comment by alas1n** [comment]
hi @gjsjohnmurray 
I have the same issue and I also using Mcafee and have gitlens(who doesn't)

**Comment by gh-egs-vividcloud** [comment]
I'm not sure what the root cause of this is but this is what I observed in the last time:

1. After I switched back to 1.77.3, everything is much better (compare to v1.78.x, but not as fast as I experienced in the past)
2. After several days, things related to the source control are slow again, even when I disable GitLens extension
3. I updated VSC to 1.78.x again, not enable GitLens -> not consistent, in some workspaces it's fast, in some others, it's slow
4. I enabled GitLens again (in VSC 1.78.x) -> still the same (not consistent)
5. I updated VSC to 1.79, with GitLens enabled -> everything is fast again (as it should be and as I experienced before), now using source control in VSC is a joy (again) to me :)

Note: in VSC 1.79, staging multiple modified files is still slow a little bit (but still good enough and acceptable, just as before) -> it would be nice if it can be as fast as when I use git bash :)

**Comment by gh-egs-vividcloud** [comment]
@chriscarreau @ChristianCiach @rafidka , maybe you should try updating VSC to the latest version (1.79) to check if the issue is resolved or not. If all of us are okay with the latest update of VSC, we can close this ticket :)

**Comment by milindgoel15** [comment]
I have just updated to 1.80 and source control takes a minute or two to load up. Whenever we open vs code before, it used to be almost instant. Although it's still better than the previous 1.78 and/or 1.79.

**Comment by meotimdihia** [comment]
The source Control tab is very slow for me. When I click to view the changed file in the tab. Happen with both MacOS and Windows. I doubt it is related to the network, but why if I use in command line it is very fast.

https://github.com/microsoft/vscode/assets/300961/57c441c5-a38c-4125-85d7-f1b5968179cb

**Comment by michmerr** [comment]
I'm trying to figure this out, too. I _think_ (at least in my case) that it might relate to the number of open files. It's running a "git ls-files --stage -- <open file>" and a "git show --textconv <open file>" for each file, along with a bunch of "git cat-file -s <commit id>". After each of these operations, it's displaying millisecond counts in the 10000 range. 

Cutting and pasting these commands into a terminal window results in fairly quick execution, so there must be something else going on (processing the output?). The commands might make sense after a sync, though why it would go through all the files that were not touched in the pull/fetch is not clear.

**Comment by milindgoel15** [comment]
I noticed if the folder opened in vscode consists of a bunch of sub git folders, the git version control will be much slower than a folder with only 1 git repository/folder.

**Comment by VSCodeTriageBot** [comment]
Hey @lszomoru, this issue might need further attention.

@gh-egs-vividcloud, you can help us out by closing this issue if the problem no longer exists, or adding more information.

**Comment by OmarShawky1** [comment]
I confirm that this issue is still occurring. 
Info:
```
$ code --version
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64

$ uname -r
5.15.0-86-generic
```

**Comment by marzojr** [comment]
I am also seeing this issue on Windows 11 Home 22H2 (build 22621.2283).

```
$ code --version
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

**Comment by ThorinEk** [comment]
I have the same problem 
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

This is an example from my Git output, certain commands are taking a very long time.
`git push origin master:master [69043ms]`

**Comment by pedrohgmacedo** [comment]
I'm having these problems as well in 1.84.0

**Comment by ZhenshengLee** [comment]
I'm having this issue in win10 pro 19045.3696, with feature experience pack 1000.19053.1000.0

$ code --version
1.82.3
fdb98833154679dbaa7af67a5a29fe19e55c2b73
x64

**Comment by IrrerPolterer** [comment]
Running VSCode `1.84.2` on Ubuntu and seeing the same thing - source control features are ridiculously slow recently. This includes the built-in git features (staging, unstaging, committing, pushing, etc. As well as extensions that tie into the git environment, like `gitlens`.

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-36-generic snap
```

**Comment by dancherb** [comment]
I'm also experiencing this - terminal windows are very slow to open since the last update, though they appear to work nicely enough once they've loaded.

**Comment by mawelsh** [comment]
code --version
1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
x64

it's unusably slow for me.  CLI is nice and speedy but anything through the UI is worthless.

**Comment by xlamb1412** [comment]
> code --version 1.84.2 [1a5daa3](https://github.com/microsoft/vscode/commit/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e) x64
> 
> it's unusably slow for me. CLI is nice and speedy but anything through the UI is worthless.

I have a same issue on Macbook M1

**Comment by vtellez** [comment]
Same issue here on Mac Sonoma with M1 Pro. Did you find any solution?

**Comment by mugilanm7** [comment]
**I have a same issue on Windows 11**  
**Is there any solution?**

code --version
1.85.1
x64

git version 2.43.0.windows.1

Edition	Windows 11 Pro
Version	23H2
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by calebjcox** [comment]
I've been running into the same thing on Windows 11.
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64

Since a couple of people mentioned that they saw issues connected to GitLens I tried disabling it and things work _much_ faster. It's a shame because the GitLens adds some useful features but that seems to be what's slowing everything down. Seems like that's the place to look for the performance issues.

**Comment by bradleyGamiMarques** [comment]
I am noticing a similar issue. I am running WSL2 on Windows 10 Enterprise Version 21H2

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

```
$ code --version
1.86.2
903b1
x64
```

I have uninstalled GitLens v14.8.2.

When I change a file in the editor and save it the integrated Git doesn't track the file unless I click the refresh button.

**Comment by bradleyGamiMarques** [comment]
> I am noticing a similar issue. I am running WSL2 on Windows 10 Enterprise Version 21H2
> 
> ```
> $ lsb_release -a
> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04.3 LTS
> Release:        22.04
> Codename:       jammy
> ```
> 
> ```
> $ code --version
> 1.86.2
> 903b1
> x64
> ```
> 
> I have uninstalled GitLens v14.8.2.
> 
> When I change a file in the editor and save it the integrated Git doesn't track the file unless I click the refresh button.

Sorry! After uninstalling GitLens I forgot to restart VSCode. This fixed my similar issue.

**Comment by maltaesousa** [comment]
Hi,
Still experiencing this problem on Code 1.87 and git 2.44.0. Reverting Code to 1.77.3 makes integrated version control fast again.
If there's anything I can do to help, let me know.

**Comment by V19Torrent** [comment]
I recently started seeing this about a month ago. I'm currently using WSL Ubuntu 22.04 and VS Code 1.87.0. Integrated GIT control takes a bout 3 minutes to startup when opening a new VS Code window, but once it finishes starting up it works perfectly.

**Comment by rainvr** [comment]
I'm not based in the US and have this problem as well.  Definitely related to source control.  Downgrading to v1.77.3 seems to have solved it for now.

**Comment by ThorinEk** [comment]
I solved this by disabling IPv6 in the network adapter settings on Windows. This also fixed npm which was also really slow/not working.

Control Panel -> Network and Internet -> Network and Sharing Centre -> Change adapter settings -> Right click on the network adapter (Ethernet in my case) -> Properties -> Uncheck the box for Internet Protocol Version 6 (TCP/IPv6).

**Comment by andrian-vangelov** [comment]
Same issue here:

Visual Studio Code
- Version: 1.87.2 (Universal)
- Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z (2 wks ago)
- Electron: 27.3.2
- ElectronBuildId: 26836302
- Chromium: 118.0.5993.159
- Node.js: 18.17.1
- V8: 11.8.172.18-electron.0
- OS: Darwin arm64 23.3.0

MacBook Air
- M2, 2022
- 16 GB
- 14.3.1 (23D60) (Sonoma)

Git
- git version 2.39.3 (Apple Git-145)
OR
- git version 2.44.0 (Homebrew)

**Comment by DDorch** [comment]
Same for me since over a week:

Some git operations lasts above 10 seconds:
```

2024-03-27 17:06:15.593 [info] > git status -z -uall [45ms]
2024-03-27 17:06:42.206 [info] > git config --get commit.template [10106ms]
2024-03-27 17:06:42.209 [info] > git ls-tree -l HEAD -- C:\DocDD\Inrae\airGR_galaxy\02-Sources\airGRiwrm\tests\testthat\test-RunModel_Ungauged.R [10111ms]
2024-03-27 17:06:42.212 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/130-ungauged-node-diversion-to-reservoir-crashes-calibration refs/remotes/130-ungauged-node-diversion-to-reservoir-crashes-calibration [10108ms]
2024-03-27 17:06:42.258 [info] > git status -z -uall [43ms]
```

Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by andrian-vangelov** [comment]
> Same issue here:
> 
> Visual Studio Code
> 
> * Version: 1.87.2 (Universal)
> * Commit: [863d258](https://github.com/microsoft/vscode/commit/863d2581ecda6849923a2118d93a088b0745d9d6)
>   Date: 2024-03-08T15:21:31.043Z (2 wks ago)
> * Electron: 27.3.2
> * ElectronBuildId: 26836302
> * Chromium: 118.0.5993.159
> * Node.js: 18.17.1
> * V8: 11.8.172.18-electron.0
> * OS: Darwin arm64 23.3.0
> 
> MacBook Air
> 
> * M2, 2022
> * 16 GB
> * 14.3.1 (23D60) (Sonoma)
> 
> Git
> 
> * git version 2.39.3 (Apple Git-145)
>   OR
> * git version 2.44.0 (Homebrew)

### It seems this issue has been fixed with:

Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

### I do not experience the sluggishness like in the previous comment.

**Comment by svenlowrybjss** [comment]
Been experiencing the same issue for a while, currently running 1.88.1 and still experience it.
Remove the GitLens extension last Friday and source control view went back to being near instant - but today it's very very slow again, so suspect the extension isn't the cause but might exacerbate it.

Running VSCode in Win11 connected to Ubuntu 22.04 instance in WSL.

**Comment by rutpshah** [comment]
For me, uninstalling GitLens made things faster.

**Comment by asaddev1011** [comment]
same issue after upgrade. I had to switch to web storm for smooth workflow. Waiting for the fix 🤞🏻

**Comment by hreeday-forYe** [comment]
I am also facing this same issue in:
Version: 1.90.0 
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
OS: Windows_NT x64 
I switched about 4 days ago
other terminal like PowerShell are working smoothly on the integrated environment however, git bash is slow. However, only running the git bash (not on vs code ) seems to be working smoothly

**Comment by White-Tomato** [comment]
I reinstalled Git Bash from Get site on Windows. Opening the terminal via the context menu in the folder opens normally. But in OUR Code, it runs for 3-5 seconds. And after each command, after they are executed, you have to wait for 5 seconds. Yesterday I was working on a project, and the terminal was open for several hours. After these few hours of work, the waiting time increased to 10-15 seconds. I also deleted it .bash_profile and .bash_history, nothing helped. How can I use Git bash terminal in VS Code without delays, as it was before? Just the other day, the waiting time began to exceed 3 seconds, which makes it impossible to continue development. (((

**Comment by gjsjohnmurray** [comment]
There is a known performance issue with git bash in 1.90. See the currently pinned issue. A fix is expected in 1.90.1.

**Comment by pietk4** [comment]
Additionally to above:

> I just saw that settings "terminal.integrated.shellIntegration.enabled" to false fix the issue. This settings seem to impact other issue related to other terminal too
> 
> #214386

In my case it fixed performance issues mentioned in this topic. Also with source control tab.

**Comment by awaluwalakhiru** [comment]
just disabled shell integration terminal may fix the issued it work for me

**Comment by luke396** [comment]
For my case, "terminal.integrated.shellIntegration.enabled" not work as expected. Performance has improved, but not totally same as before.

**Comment by Sujit-Ingenio** [comment]
Setting `terminal.integrated.shellIntegration.enabled` to `false` fixes this issue as mentioned in #212090 and #214407 .

**Comment by Bro3x** [comment]
Same here. Impossible to work with. We're getting 33426 ms and more response times. 
It is only during initialisation. After waiting approximately 15 minutes all is fine.
During that period there is a lot of network traffic on the interface. Around 2.5 Gbit (3Mbit/second).
Native git-client in Windows 11 acts fine.

```
git count-objects -vH
count: 391
size: 611.57 KiB
in-pack: 13883
packs: 1
size-pack: 3.22 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```
```
2024-07-08 17:35:58.410 [info] > git symbolic-ref --short refs/remotes/origin/HEAD [417ms]
2024-07-08 17:35:58.410 [info] fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
2024-07-08 17:35:58.410 [info] GitHistoryProvider:resolveHistoryItemGroupBase - Failed to resolve history item group base for 'refs/heads/develop'
2024-07-08 17:35:58.410 [info] GitHistoryProvider:resolveHistoryItemGroupCommonAncestor - Failed to resolve history item group base for 'refs/heads/develop'
2024-07-08 17:35:58.676 [info] > git cat-file -s 16f10ef654440266051f93847f83b08c6d67cc71 [1350ms]
2024-07-08 17:35:59.547 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/develop [1110ms]
2024-07-08 17:36:00.475 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/develop [925ms]
2024-07-08 17:36:02.606 [info] > git config --local branch.develop.vscode-merge-base [2064ms]
2024-07-08 17:36:02.606 [warning] git config failed: Failed to execute git
2024-07-08 17:36:03.402 [info] > git status -z -uall [33426ms]
2024-07-08 17:36:05.519 [info] > git reflog refs/heads/develop --grep-reflog=branch: Created from *. [2766ms]
2024-07-08 17:36:08.803 [info] > git reflog HEAD --grep-reflog=checkout: moving from .* to develop [3136ms]
```
```
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by avengerx** [comment]
I was having a similar issue here. VSCode's called `git.exe`  process was eating up all system resources and taking ages to complete -- only to then be called again.

In my case I could notice only the `git reflog` command was taking long time and resources (and memory) to run.

<details><summary>VSCode Git Console log</summary>

```
2024-08-21 19:41:02.457 [info] > git status -z -uall [98ms]
2024-08-21 19:41:02.540 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/master refs/remotes/master [72ms]
2024-08-21 19:41:02.628 [info] > git config --local branch.master.vscode-merge-base [80ms]
2024-08-21 19:41:02.628 [warning] [Git][config] git config failed: Failed to execute git
2024-08-21 19:43:35.516 [info] > git reflog master --grep-reflog=branch: Created from *. [166808ms]
2024-08-21 19:43:35.547 [info] > git reflog master --grep-reflog=branch: Created from *. [167047ms]
2024-08-21 19:43:35.621 [info] > git symbolic-ref --short refs/remotes/origin/HEAD [96ms]
2024-08-21 19:43:35.621 [info] fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
2024-08-21 19:43:35.649 [info] > git symbolic-ref --short refs/remotes/origin/HEAD [93ms]
2024-08-21 19:43:35.649 [info] fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
2024-08-21 19:43:35.726 [info] > git merge-base refs/heads/master refs/remotes/origin/master [96ms]
2024-08-21 19:43:35.810 [info] > git -c core.longpaths=true rev-list --count --left-right refs/heads/master...refs/remotes/origin/master [74ms]
2024-08-21 19:43:35.882 [info] > git diff --name-status -z --diff-filter=ADMR c39d29fb60ea50d5dfe4ec65fd99cc6ab47d394b...refs/remotes/origin/master [64ms]
2024-08-21 19:43:48.197 [info] > git reflog master --grep-reflog=branch: Created from *. [165559ms]
2024-08-21 19:43:48.277 [info] > git symbolic-ref --short refs/remotes/origin/HEAD [71ms]
2024-08-21 19:43:48.277 [info] fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
2024-08-21 19:49:50.672 [info] > git config --get commit.template [90ms]
```
</details>

Turns out my repo's `.git/logs/refs/heads/master` file was 2GB big, such like
```
$ du -sh .git
2.1G    .git
# (...) dig thru the directory structure (...)
$ du -sh logs/refs/heads/*
2.1G    logs/refs/heads/master
```

That was a brand new repository, 2MB worth of data, 3 commits total to its single `master` branch, no big bloat-cleaning commits. So, there was no reason the repo had a 2GB big log. I then found this issue and tried to disable git. Of course it fixed the CPU load. `terminal.integrated.shellIntegration.enabled=false` didn't help, as I still saw `git reflog` commands run.

Then I realized, as all that log was bloat, all I needed to do was

`git gc`

And voila

```
$ du -sh .git
618K    .git
```

And VSCode was back to speed. In case anybody else face this issue and, like me, ends up in this GitHub Issue, `git-gc` was the solution. I still have no idea why the repo log grew up so much in so little time (repo created today).

My VSCode version info:
```
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
```

**Comment by sascharo** [comment]
I'm on 1.93.0 and just started to experience these slowdowns for the past two days when working with Rust and Burn. `git gc` did not solve the issue for me, but removing the [Trunk](https://marketplace.visualstudio.com/items?itemName=Trunk.io) extension or editing the default `.gitignore` in the `.trunk` folder within the project did. The extension locks up certain aspects of my VSC like git when the project directory contains a ton of training and validation logs from Burn.

**Comment by Soily** [comment]
I'm still experiencing the issue with the latest version 1.94.1.
Beside what was already mentioned here, I'm also not able to see the difference of my changed files for ages. Sometimes after 20 Minutes or so, it will suddenly show me the differences, but in such a state it's very much unusable for productive work.

**Comment by cesaryuan** [comment]
> Setting `terminal.integrated.shellIntegration.enabled` to `false` fixes this issue as mentioned in [#212090](https://github.com/microsoft/vscode/issues/212090) and [#214407](https://github.com/microsoft/vscode/issues/214407) .

Thanks! This fixes it. I think more people should see it.

**Comment by ananth-iyer** [comment]
I am having same issue in latest version 1.94 and Insider version 1.95.
if you open multiple files from diff then it reproducible.

**Comment by SomeRandomUsern4m3** [comment]
I'm experiencing this issue on  the latest release version of vscode(1.95), it has taken upwards of 20 minutes to commit to the main branch and is still committing.

**Comment by sysmat** [comment]
the same 1.95.2

**Comment by Anoerak** [comment]
Same for me:
`Version: 1.95.3 (Universal)`

It happens every time I compile (webpack.mix). Closing VS Code is the only solution to release CPU and allow the task to pursue. 
Quite annoying in prod.

**Comment by aknaian** [comment]
When I run du -sh .git, I get 6 GB, before and after running git gc.  However, after running git gc, this problem is 100% fixed for me, and git is fast again from the lastest version (1.95.3) of vscode in WSL2 on Windows 11.

**Comment by thisis-dc4** [comment]
I was facing the same issue and in the past I had enabled the `terminal.integrated.suggest.enabled` setting which is currently experimental. Disabling it seemed to fix the problem for me.

**Comment by Soily** [comment]
> I was facing the same issue and in the past I had enabled the `terminal.integrated.suggest.enabled` setting which is currently experimental. Disabling it seemed to fix the problem for me.

This I already applied a couple of month ago, but it didn't solve it for me.

**Comment by DominicBortmes** [comment]
Sharing how to disable Source Control as the issue persists for me since a long time on different OS and VS Code versions. 

Add  `"git.enabled": false` to your settings.json. This makes your vscode and integrated terminal work again and not further block for 10+ seconds on smaller workspaces.

Kudos: https://github.com/Microsoft/vscode/issues/35475#issuecomment-347547071

**Comment by Masty88** [comment]
> I've been running into the same thing on Windows 11. 1.85.1 [0ee08df](https://github.com/microsoft/vscode/commit/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2) x64
> 
> Since a couple of people mentioned that they saw issues connected to GitLens I tried disabling it and things work _much_ faster. It's a shame because the GitLens adds some useful features but that seems to be what's slowing everything down. Seems like that's the place to look for the performance issues.

Yes disable git lens make it faster for me too apparently is the only workaround for the moment
```
Version: 1.98.2 (system setup)
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Windows_NT x64 10.0.26100
```

**Comment by gjsjohnmurray** [comment]
@Gilfoyle-sy does the advice in #216815 help you?

**Comment by Gilfoyle-sy** [comment]
@gjsjohnmurray 
thank you for your suggestion， i will try it.
and I reinstalled vscode before, source control  getting faster than before
i dont know why ,but now, i can use source control  :-)

**Comment by cbrim-12** [comment]
Facing the same issue, reinstalled, but that does not help.

**Comment by marcoschou** [comment]
I am also facing the same issue. Disabling GitLens did not help.

**Comment by alumni** [comment]
I've got the same issue on Linux over the past few months, and it's making making vscode unusable for about a minute every now and then. This happens when I try to checkout the master branch:

```shell
2025-06-22 14:29:54.145 [info] > git for-each-ref --sort -committerdate --format %(refname)%00%(objectname)%00%(*objectname)%00%(parent)%00%(*parent)%00%(authorname)%00%(*authorname)%00%(committerdate:unix)%00%(*committerdate:unix)%00%(subject)%00%(*subject)%00%(upstream:track) [3ms]
2025-06-22 14:31:09.714 [info] > git checkout -q master [400ms]
```

Other times, something similar happens a bit earlier, before I even get to the branch selections - the branch selection menu opens with ~1 minute delay when I click the branch in the status bar.

I don't have GitLens (I figured out it's junk long time ago). Changing `terminal.integrated.shellIntegration.enabled` does not help.

**Comment by median-dxz** [comment]
I've encountered this issue for about one month, and today is the first time I searched for this issue on Google. To my surprise, I found that it's not even a clear issue that can explain what happened — it's just broken, which is really sad.

From my perspective:
 1. Executing `git gc` doesn't help.
 2. Turn off `terminal.integrated.shellIntegration.enabled` doesn't change anything.
 3. And I haven't installed GitLens either.
 4. The most important thing is that it's not only the git integration that's very slow, but git-bash itself is also extremely slow on VS Code’s integrated terminal.

Just try testing this command: `time date +%S.%N`

There is a huge difference between running the command elsewhere and inside VS Code’s integrated terminal using git-bash.

From the system default shell:

<img width="243" height="93" alt="Image" src="https://github.com/user-attachments/assets/1f5c2e2f-a6ab-46b5-9c8b-5479705f645b" />

Inside VS Code:

<img width="195" height="103" alt="Image" src="https://github.com/user-attachments/assets/6379171a-acf3-4e3d-987c-fdf78b8b60e1" />

It's really unacceptable. I hope some progress can be made here as soon as possible.

```shell
1.103.0
e3550cfac4b63ca4eafca7b601f0d2885817fd1f
x64
```

**Comment by Maxim-Mazurok** [comment]
My git in WSL2 (Ubuntu on Windows) is also acting up.
Sometimes it takes a while to load changes.
Now I'm seeing loading/clock indicator flashing every few seconds, this is what I see in the logs:
```
2025-08-29 03:39:30.214 [info] > git config --get commit.template [1ms]
2025-08-29 03:39:30.291 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [2ms]
2025-08-29 03:39:30.427 [info] > git status -z -uall [11ms]
2025-08-29 03:39:30.428 [info] > git for-each-ref --sort -committerdate --format %(refname)%00%(objectname)%00%(*objectname) [2ms]
2025-08-29 03:39:30.980 [info] > git rev-parse --show-toplevel [2ms]
2025-08-29 03:39:35.477 [info] > git config --get commit.template [1ms]
2025-08-29 03:39:35.593 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [2ms]
2025-08-29 03:39:35.835 [info] > git status -z -uall [15ms]
2025-08-29 03:39:35.836 [info] > git for-each-ref --sort -committerdate --format %(refname)%00%(objectname)%00%(*objectname) [2ms]
2025-08-29 03:39:36.384 [info] > git rev-parse --show-toplevel [1ms]
2025-08-29 03:39:40.889 [info] > git config --get commit.template [3ms]
2025-08-29 03:39:40.968 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [2ms]
2025-08-29 03:39:41.132 [info] > git status -z -uall [11ms]
2025-08-29 03:39:41.133 [info] > git for-each-ref --sort -committerdate --format %(refname)%00%(objectname)%00%(*objectname) [2ms]
2025-08-29 03:39:41.672 [info] > git rev-parse --show-toplevel [1ms]
```

**Comment by cesaryuan** [comment]
Provide a new potential solution (different from all methods mentioned above): Disable and Stop Windows service `Microsoft PC Manager Service` @median-dxz

**Comment by median-dxz** [comment]
Sorry for the late comment—but actually, this issue has disappeared on my machine (it’s been fine for over a week now), and I didn't do anything special. Currently, the Git integration in my VSCode responds as fast as expected (really fast!).

My current VSCode version is:

```text
Version: 1.104.2 (user setup)
Commit: e3a5acfb517a443235981655413d566533107e92
Date: 2025-09-24T11:21:37.073Z
Electron: 37.3.1
ElectronBuildId: 12404162
Chromium: 138.0.7204.235
Node.js: 22.18.0
V8: 13.8.258.31-electron.0
OS: Windows_NT x64 10.0.26100
```

@cesaryuan @constantinoflouras

**Comment by dokugo** [comment]
Currently encountering this issue in a very small repo.

```
2025-10-07 16:32:07.885 [info] > git status -z -uall [30223ms]
2025-10-07 16:32:11.081 [info] > git diff --name-status -z --diff-filter=ADMR a2cf410cb365dfb8e7ea2352759078eca3ddbe98 [30234ms]
2025-10-07 16:35:53.099 [info] > git show --textconv :src/app/main.tsx [30234ms]
2025-10-07 16:36:12.815 [info] > git check-ignore -v -z --stdin [30233ms]
2025-10-07 16:38:13.575 [info] > git ls-files --stage -- src/lib/query/provider.tsx [30229ms]
2025-10-07 16:38:40.815 [info] > git fetch [31650ms]
```

1. Executing `git gc` doesn't help.
2. Turning off `terminal.integrated.shellIntegration.enabled` doesn't help.
3. No git-related extensions.

```
Version: 1.104.3 (user setup)
Commit: 385651c938df8a906869babee516bffd0ddb9829
Date: 2025-10-02T12:30:51.747Z
Electron: 37.3.1
ElectronBuildId: 12404162
Chromium: 138.0.7204.235
Node.js: 22.18.0
V8: 13.8.258.31-electron.0
OS: Windows_NT x64 10.0.26100
```

**Comment by dokugo** [comment]
@median-dxz
Oh, my bad, I forgot to check the git version. After updating from 2.45.2.windows.1 to 2.51.0.windows.2, the problem is gone now. Thanks!
